# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(853, 830)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.scrollArea = QtWidgets.QScrollArea(self.splitter)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 411, 766))
        self.scrollAreaWidgetContents.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.listWidget = QtWidgets.QListWidget(self.scrollAreaWidgetContents)
        self.listWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout_2.addWidget(self.listWidget)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.scrollArea_2 = QtWidgets.QScrollArea(self.splitter)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setEnabled(False)
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 402, 2968))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.saveQuizButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.saveQuizButton.setObjectName("saveQuizButton")
        self.horizontalLayout.addWidget(self.saveQuizButton)
        self.resetQuizButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.resetQuizButton.setObjectName("resetQuizButton")
        self.horizontalLayout.addWidget(self.resetQuizButton)
        self.gridLayout_4.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.quizVerticalLayout = QtWidgets.QVBoxLayout()
        self.quizVerticalLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.quizVerticalLayout.setContentsMargins(1, 1, 1, 1)
        self.quizVerticalLayout.setSpacing(20)
        self.quizVerticalLayout.setObjectName("quizVerticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.titleLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.titleLabel.setObjectName("titleLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.titleLabel)
        self.titleLineEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.titleLineEdit.setObjectName("titleLineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.titleLineEdit)
        self.subtitleLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.subtitleLabel.setObjectName("subtitleLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.subtitleLabel)
        self.subtitleLineEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.subtitleLineEdit.setObjectName("subtitleLineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.subtitleLineEdit)
        self.authorLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.authorLabel.setObjectName("authorLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.authorLabel)
        self.authorLineEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.authorLineEdit.setObjectName("authorLineEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.authorLineEdit)
        self.publishOnLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.publishOnLabel.setObjectName("publishOnLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.publishOnLabel)
        self.publishOnDateEdit = QtWidgets.QDateEdit(self.scrollAreaWidgetContents_2)
        self.publishOnDateEdit.setCalendarPopup(True)
        self.publishOnDateEdit.setObjectName("publishOnDateEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.publishOnDateEdit)
        self.quizVerticalLayout.addLayout(self.formLayout)
        self.line = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.quizVerticalLayout.addWidget(self.line)
        self.q1VerticalLayout = QtWidgets.QVBoxLayout()
        self.q1VerticalLayout.setObjectName("q1VerticalLayout")
        self.q1Question1Label = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        self.q1Question1Label.setFont(font)
        self.q1Question1Label.setObjectName("q1Question1Label")
        self.q1VerticalLayout.addWidget(self.q1Question1Label)
        self.q1QuestionTextEdit = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_2)
        self.q1QuestionTextEdit.setObjectName("q1QuestionTextEdit")
        self.q1VerticalLayout.addWidget(self.q1QuestionTextEdit)
        self.q1ChoiceGroupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_2)
        self.q1ChoiceGroupBox.setMinimumSize(QtCore.QSize(0, 200))
        self.q1ChoiceGroupBox.setObjectName("q1ChoiceGroupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.q1ChoiceGroupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.q1ChoiceHorizontalLayout_1 = QtWidgets.QHBoxLayout()
        self.q1ChoiceHorizontalLayout_1.setObjectName("q1ChoiceHorizontalLayout_1")
        self.q1ChoiceRadioButton_1 = QtWidgets.QRadioButton(self.q1ChoiceGroupBox)
        self.q1ChoiceRadioButton_1.setText("")
        self.q1ChoiceRadioButton_1.setObjectName("q1ChoiceRadioButton_1")
        self.q1ChoiceHorizontalLayout_1.addWidget(self.q1ChoiceRadioButton_1)
        self.q1Choice1LineEdit_1 = QtWidgets.QLineEdit(self.q1ChoiceGroupBox)
        self.q1Choice1LineEdit_1.setObjectName("q1Choice1LineEdit_1")
        self.q1ChoiceHorizontalLayout_1.addWidget(self.q1Choice1LineEdit_1)
        self.gridLayout_3.addLayout(self.q1ChoiceHorizontalLayout_1, 0, 0, 1, 1)
        self.q1ChoiceHorizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.q1ChoiceHorizontalLayout_2.setObjectName("q1ChoiceHorizontalLayout_2")
        self.q1ChoiceRadioButton_2 = QtWidgets.QRadioButton(self.q1ChoiceGroupBox)
        self.q1ChoiceRadioButton_2.setText("")
        self.q1ChoiceRadioButton_2.setObjectName("q1ChoiceRadioButton_2")
        self.q1ChoiceHorizontalLayout_2.addWidget(self.q1ChoiceRadioButton_2)
        self.q1Choice1LineEdit_2 = QtWidgets.QLineEdit(self.q1ChoiceGroupBox)
        self.q1Choice1LineEdit_2.setObjectName("q1Choice1LineEdit_2")
        self.q1ChoiceHorizontalLayout_2.addWidget(self.q1Choice1LineEdit_2)
        self.gridLayout_3.addLayout(self.q1ChoiceHorizontalLayout_2, 1, 0, 1, 1)
        self.q1ChoiceHorizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.q1ChoiceHorizontalLayout_3.setObjectName("q1ChoiceHorizontalLayout_3")
        self.q1ChoiceRadioButton_3 = QtWidgets.QRadioButton(self.q1ChoiceGroupBox)
        self.q1ChoiceRadioButton_3.setText("")
        self.q1ChoiceRadioButton_3.setObjectName("q1ChoiceRadioButton_3")
        self.q1ChoiceHorizontalLayout_3.addWidget(self.q1ChoiceRadioButton_3)
        self.q1Choice1LineEdit_3 = QtWidgets.QLineEdit(self.q1ChoiceGroupBox)
        self.q1Choice1LineEdit_3.setObjectName("q1Choice1LineEdit_3")
        self.q1ChoiceHorizontalLayout_3.addWidget(self.q1Choice1LineEdit_3)
        self.gridLayout_3.addLayout(self.q1ChoiceHorizontalLayout_3, 2, 0, 1, 1)
        self.q1ChoiceHorizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.q1ChoiceHorizontalLayout_4.setObjectName("q1ChoiceHorizontalLayout_4")
        self.q1ChoiceRadioButton_4 = QtWidgets.QRadioButton(self.q1ChoiceGroupBox)
        self.q1ChoiceRadioButton_4.setText("")
        self.q1ChoiceRadioButton_4.setObjectName("q1ChoiceRadioButton_4")
        self.q1ChoiceHorizontalLayout_4.addWidget(self.q1ChoiceRadioButton_4)
        self.q1Choice1LineEdit_4 = QtWidgets.QLineEdit(self.q1ChoiceGroupBox)
        self.q1Choice1LineEdit_4.setObjectName("q1Choice1LineEdit_4")
        self.q1ChoiceHorizontalLayout_4.addWidget(self.q1Choice1LineEdit_4)
        self.gridLayout_3.addLayout(self.q1ChoiceHorizontalLayout_4, 3, 0, 1, 1)
        self.q1VerticalLayout.addWidget(self.q1ChoiceGroupBox)
        self.q1Answer1abel = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.q1Answer1abel.setObjectName("q1Answer1abel")
        self.q1VerticalLayout.addWidget(self.q1Answer1abel)
        self.q1AnswerTextEdit = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_2)
        self.q1AnswerTextEdit.setObjectName("q1AnswerTextEdit")
        self.q1VerticalLayout.addWidget(self.q1AnswerTextEdit)
        self.q1ImageUrlLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.q1ImageUrlLabel.setObjectName("q1ImageUrlLabel")
        self.q1VerticalLayout.addWidget(self.q1ImageUrlLabel)
        self.q1ImageUrlLineEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.q1ImageUrlLineEdit.setObjectName("q1ImageUrlLineEdit")
        self.q1VerticalLayout.addWidget(self.q1ImageUrlLineEdit)
        self.q1ImageCaptionLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.q1ImageCaptionLabel.setObjectName("q1ImageCaptionLabel")
        self.q1VerticalLayout.addWidget(self.q1ImageCaptionLabel)
        self.q1ImageCaptionLineEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.q1ImageCaptionLineEdit.setObjectName("q1ImageCaptionLineEdit")
        self.q1VerticalLayout.addWidget(self.q1ImageCaptionLineEdit)
        self.quizVerticalLayout.addLayout(self.q1VerticalLayout)
        self.line_2 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.quizVerticalLayout.addWidget(self.line_2)
        self.q2VerticalLayout = QtWidgets.QVBoxLayout()
        self.q2VerticalLayout.setObjectName("q2VerticalLayout")
        self.q2VerticalLayout1 = QtWidgets.QVBoxLayout()
        self.q2VerticalLayout1.setObjectName("q2VerticalLayout1")
        self.q2Question1Label = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        self.q2Question1Label.setFont(font)
        self.q2Question1Label.setObjectName("q2Question1Label")
        self.q2VerticalLayout1.addWidget(self.q2Question1Label)
        self.q2QuestionTextEdit = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_2)
        self.q2QuestionTextEdit.setObjectName("q2QuestionTextEdit")
        self.q2VerticalLayout1.addWidget(self.q2QuestionTextEdit)
        self.q2ChoiceGroupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_2)
        self.q2ChoiceGroupBox.setMinimumSize(QtCore.QSize(0, 200))
        self.q2ChoiceGroupBox.setObjectName("q2ChoiceGroupBox")
        self.gridLayout_31 = QtWidgets.QGridLayout(self.q2ChoiceGroupBox)
        self.gridLayout_31.setObjectName("gridLayout_31")
        self.q2ChoiceHorizontalLayout_1 = QtWidgets.QHBoxLayout()
        self.q2ChoiceHorizontalLayout_1.setObjectName("q2ChoiceHorizontalLayout_1")
        self.q2ChoiceRadioButton_1 = QtWidgets.QRadioButton(self.q2ChoiceGroupBox)
        self.q2ChoiceRadioButton_1.setText("")
        self.q2ChoiceRadioButton_1.setObjectName("q2ChoiceRadioButton_1")
        self.q2ChoiceHorizontalLayout_1.addWidget(self.q2ChoiceRadioButton_1)
        self.q2Choice1LineEdit_1 = QtWidgets.QLineEdit(self.q2ChoiceGroupBox)
        self.q2Choice1LineEdit_1.setObjectName("q2Choice1LineEdit_1")
        self.q2ChoiceHorizontalLayout_1.addWidget(self.q2Choice1LineEdit_1)
        self.gridLayout_31.addLayout(self.q2ChoiceHorizontalLayout_1, 0, 0, 1, 1)
        self.q2ChoiceHorizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.q2ChoiceHorizontalLayout_2.setObjectName("q2ChoiceHorizontalLayout_2")
        self.q2ChoiceRadioButton_2 = QtWidgets.QRadioButton(self.q2ChoiceGroupBox)
        self.q2ChoiceRadioButton_2.setText("")
        self.q2ChoiceRadioButton_2.setObjectName("q2ChoiceRadioButton_2")
        self.q2ChoiceHorizontalLayout_2.addWidget(self.q2ChoiceRadioButton_2)
        self.q2Choice1LineEdit_2 = QtWidgets.QLineEdit(self.q2ChoiceGroupBox)
        self.q2Choice1LineEdit_2.setObjectName("q2Choice1LineEdit_2")
        self.q2ChoiceHorizontalLayout_2.addWidget(self.q2Choice1LineEdit_2)
        self.gridLayout_31.addLayout(self.q2ChoiceHorizontalLayout_2, 1, 0, 1, 1)
        self.q2ChoiceHorizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.q2ChoiceHorizontalLayout_3.setObjectName("q2ChoiceHorizontalLayout_3")
        self.q2ChoiceRadioButton_3 = QtWidgets.QRadioButton(self.q2ChoiceGroupBox)
        self.q2ChoiceRadioButton_3.setText("")
        self.q2ChoiceRadioButton_3.setObjectName("q2ChoiceRadioButton_3")
        self.q2ChoiceHorizontalLayout_3.addWidget(self.q2ChoiceRadioButton_3)
        self.q2Choice1LineEdit_3 = QtWidgets.QLineEdit(self.q2ChoiceGroupBox)
        self.q2Choice1LineEdit_3.setObjectName("q2Choice1LineEdit_3")
        self.q2ChoiceHorizontalLayout_3.addWidget(self.q2Choice1LineEdit_3)
        self.gridLayout_31.addLayout(self.q2ChoiceHorizontalLayout_3, 2, 0, 1, 1)
        self.q2ChoiceHorizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.q2ChoiceHorizontalLayout_4.setObjectName("q2ChoiceHorizontalLayout_4")
        self.q2ChoiceRadioButton_4 = QtWidgets.QRadioButton(self.q2ChoiceGroupBox)
        self.q2ChoiceRadioButton_4.setText("")
        self.q2ChoiceRadioButton_4.setObjectName("q2ChoiceRadioButton_4")
        self.q2ChoiceHorizontalLayout_4.addWidget(self.q2ChoiceRadioButton_4)
        self.q2Choice1LineEdit_4 = QtWidgets.QLineEdit(self.q2ChoiceGroupBox)
        self.q2Choice1LineEdit_4.setObjectName("q2Choice1LineEdit_4")
        self.q2ChoiceHorizontalLayout_4.addWidget(self.q2Choice1LineEdit_4)
        self.gridLayout_31.addLayout(self.q2ChoiceHorizontalLayout_4, 3, 0, 1, 1)
        self.q2VerticalLayout1.addWidget(self.q2ChoiceGroupBox)
        self.q2Answer1abel = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.q2Answer1abel.setObjectName("q2Answer1abel")
        self.q2VerticalLayout1.addWidget(self.q2Answer1abel)
        self.q2AnswerTextEdit = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_2)
        self.q2AnswerTextEdit.setObjectName("q2AnswerTextEdit")
        self.q2VerticalLayout1.addWidget(self.q2AnswerTextEdit)
        self.q2ImageUrlLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.q2ImageUrlLabel.setObjectName("q2ImageUrlLabel")
        self.q2VerticalLayout1.addWidget(self.q2ImageUrlLabel)
        self.q2ImageUrlLineEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.q2ImageUrlLineEdit.setObjectName("q2ImageUrlLineEdit")
        self.q2VerticalLayout1.addWidget(self.q2ImageUrlLineEdit)
        self.q2ImageCaptionLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.q2ImageCaptionLabel.setObjectName("q2ImageCaptionLabel")
        self.q2VerticalLayout1.addWidget(self.q2ImageCaptionLabel)
        self.q2ImageCaptionLineEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.q2ImageCaptionLineEdit.setObjectName("q2ImageCaptionLineEdit")
        self.q2VerticalLayout1.addWidget(self.q2ImageCaptionLineEdit)
        self.q2VerticalLayout.addLayout(self.q2VerticalLayout1)
        self.quizVerticalLayout.addLayout(self.q2VerticalLayout)
        self.line_3 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.quizVerticalLayout.addWidget(self.line_3)
        self.q3VerticalLayout = QtWidgets.QVBoxLayout()
        self.q3VerticalLayout.setObjectName("q3VerticalLayout")
        self.q3VerticalLayout1 = QtWidgets.QVBoxLayout()
        self.q3VerticalLayout1.setObjectName("q3VerticalLayout1")
        self.q3Question1Label = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        self.q3Question1Label.setFont(font)
        self.q3Question1Label.setObjectName("q3Question1Label")
        self.q3VerticalLayout1.addWidget(self.q3Question1Label)
        self.q3QuestionTextEdit = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_2)
        self.q3QuestionTextEdit.setObjectName("q3QuestionTextEdit")
        self.q3VerticalLayout1.addWidget(self.q3QuestionTextEdit)
        self.q3ChoiceGroupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_2)
        self.q3ChoiceGroupBox.setMinimumSize(QtCore.QSize(0, 200))
        self.q3ChoiceGroupBox.setObjectName("q3ChoiceGroupBox")
        self.gridLayout_32 = QtWidgets.QGridLayout(self.q3ChoiceGroupBox)
        self.gridLayout_32.setObjectName("gridLayout_32")
        self.q3ChoiceHorizontalLayout_1 = QtWidgets.QHBoxLayout()
        self.q3ChoiceHorizontalLayout_1.setObjectName("q3ChoiceHorizontalLayout_1")
        self.q3ChoiceRadioButton_1 = QtWidgets.QRadioButton(self.q3ChoiceGroupBox)
        self.q3ChoiceRadioButton_1.setText("")
        self.q3ChoiceRadioButton_1.setObjectName("q3ChoiceRadioButton_1")
        self.q3ChoiceHorizontalLayout_1.addWidget(self.q3ChoiceRadioButton_1)
        self.q3Choice1LineEdit_1 = QtWidgets.QLineEdit(self.q3ChoiceGroupBox)
        self.q3Choice1LineEdit_1.setObjectName("q3Choice1LineEdit_1")
        self.q3ChoiceHorizontalLayout_1.addWidget(self.q3Choice1LineEdit_1)
        self.gridLayout_32.addLayout(self.q3ChoiceHorizontalLayout_1, 0, 0, 1, 1)
        self.q3ChoiceHorizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.q3ChoiceHorizontalLayout_2.setObjectName("q3ChoiceHorizontalLayout_2")
        self.q3ChoiceRadioButton_2 = QtWidgets.QRadioButton(self.q3ChoiceGroupBox)
        self.q3ChoiceRadioButton_2.setText("")
        self.q3ChoiceRadioButton_2.setObjectName("q3ChoiceRadioButton_2")
        self.q3ChoiceHorizontalLayout_2.addWidget(self.q3ChoiceRadioButton_2)
        self.q3Choice1LineEdit_2 = QtWidgets.QLineEdit(self.q3ChoiceGroupBox)
        self.q3Choice1LineEdit_2.setObjectName("q3Choice1LineEdit_2")
        self.q3ChoiceHorizontalLayout_2.addWidget(self.q3Choice1LineEdit_2)
        self.gridLayout_32.addLayout(self.q3ChoiceHorizontalLayout_2, 1, 0, 1, 1)
        self.q3ChoiceHorizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.q3ChoiceHorizontalLayout_3.setObjectName("q3ChoiceHorizontalLayout_3")
        self.q3ChoiceRadioButton_3 = QtWidgets.QRadioButton(self.q3ChoiceGroupBox)
        self.q3ChoiceRadioButton_3.setText("")
        self.q3ChoiceRadioButton_3.setObjectName("q3ChoiceRadioButton_3")
        self.q3ChoiceHorizontalLayout_3.addWidget(self.q3ChoiceRadioButton_3)
        self.q3Choice1LineEdit_3 = QtWidgets.QLineEdit(self.q3ChoiceGroupBox)
        self.q3Choice1LineEdit_3.setObjectName("q3Choice1LineEdit_3")
        self.q3ChoiceHorizontalLayout_3.addWidget(self.q3Choice1LineEdit_3)
        self.gridLayout_32.addLayout(self.q3ChoiceHorizontalLayout_3, 2, 0, 1, 1)
        self.q3ChoiceHorizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.q3ChoiceHorizontalLayout_4.setObjectName("q3ChoiceHorizontalLayout_4")
        self.q3ChoiceRadioButton_4 = QtWidgets.QRadioButton(self.q3ChoiceGroupBox)
        self.q3ChoiceRadioButton_4.setText("")
        self.q3ChoiceRadioButton_4.setObjectName("q3ChoiceRadioButton_4")
        self.q3ChoiceHorizontalLayout_4.addWidget(self.q3ChoiceRadioButton_4)
        self.q3Choice1LineEdit_4 = QtWidgets.QLineEdit(self.q3ChoiceGroupBox)
        self.q3Choice1LineEdit_4.setObjectName("q3Choice1LineEdit_4")
        self.q3ChoiceHorizontalLayout_4.addWidget(self.q3Choice1LineEdit_4)
        self.gridLayout_32.addLayout(self.q3ChoiceHorizontalLayout_4, 3, 0, 1, 1)
        self.q3VerticalLayout1.addWidget(self.q3ChoiceGroupBox)
        self.q3Answer1abel = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.q3Answer1abel.setObjectName("q3Answer1abel")
        self.q3VerticalLayout1.addWidget(self.q3Answer1abel)
        self.q3AnswerTextEdit = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_2)
        self.q3AnswerTextEdit.setObjectName("q3AnswerTextEdit")
        self.q3VerticalLayout1.addWidget(self.q3AnswerTextEdit)
        self.q3ImageUrlLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.q3ImageUrlLabel.setObjectName("q3ImageUrlLabel")
        self.q3VerticalLayout1.addWidget(self.q3ImageUrlLabel)
        self.q3ImageUrlLineEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.q3ImageUrlLineEdit.setObjectName("q3ImageUrlLineEdit")
        self.q3VerticalLayout1.addWidget(self.q3ImageUrlLineEdit)
        self.q3ImageCaptionLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.q3ImageCaptionLabel.setObjectName("q3ImageCaptionLabel")
        self.q3VerticalLayout1.addWidget(self.q3ImageCaptionLabel)
        self.q3ImageCaptionLineEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.q3ImageCaptionLineEdit.setObjectName("q3ImageCaptionLineEdit")
        self.q3VerticalLayout1.addWidget(self.q3ImageCaptionLineEdit)
        self.q3VerticalLayout.addLayout(self.q3VerticalLayout1)
        self.quizVerticalLayout.addLayout(self.q3VerticalLayout)
        self.line_4 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.quizVerticalLayout.addWidget(self.line_4)
        self.q4VerticalLayout = QtWidgets.QVBoxLayout()
        self.q4VerticalLayout.setObjectName("q4VerticalLayout")
        self.q4Question1Label = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        self.q4Question1Label.setFont(font)
        self.q4Question1Label.setObjectName("q4Question1Label")
        self.q4VerticalLayout.addWidget(self.q4Question1Label)
        self.q4QuestionTextEdit = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_2)
        self.q4QuestionTextEdit.setObjectName("q4QuestionTextEdit")
        self.q4VerticalLayout.addWidget(self.q4QuestionTextEdit)
        self.q4ChoiceGroupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_2)
        self.q4ChoiceGroupBox.setMinimumSize(QtCore.QSize(0, 200))
        self.q4ChoiceGroupBox.setObjectName("q4ChoiceGroupBox")
        self.gridLayout_33 = QtWidgets.QGridLayout(self.q4ChoiceGroupBox)
        self.gridLayout_33.setObjectName("gridLayout_33")
        self.q4ChoiceHorizontalLayout_1 = QtWidgets.QHBoxLayout()
        self.q4ChoiceHorizontalLayout_1.setObjectName("q4ChoiceHorizontalLayout_1")
        self.q4ChoiceRadioButton_1 = QtWidgets.QRadioButton(self.q4ChoiceGroupBox)
        self.q4ChoiceRadioButton_1.setText("")
        self.q4ChoiceRadioButton_1.setObjectName("q4ChoiceRadioButton_1")
        self.q4ChoiceHorizontalLayout_1.addWidget(self.q4ChoiceRadioButton_1)
        self.q4Choice1LineEdit_1 = QtWidgets.QLineEdit(self.q4ChoiceGroupBox)
        self.q4Choice1LineEdit_1.setObjectName("q4Choice1LineEdit_1")
        self.q4ChoiceHorizontalLayout_1.addWidget(self.q4Choice1LineEdit_1)
        self.gridLayout_33.addLayout(self.q4ChoiceHorizontalLayout_1, 0, 0, 1, 1)
        self.q4ChoiceHorizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.q4ChoiceHorizontalLayout_2.setObjectName("q4ChoiceHorizontalLayout_2")
        self.q4ChoiceRadioButton_2 = QtWidgets.QRadioButton(self.q4ChoiceGroupBox)
        self.q4ChoiceRadioButton_2.setText("")
        self.q4ChoiceRadioButton_2.setObjectName("q4ChoiceRadioButton_2")
        self.q4ChoiceHorizontalLayout_2.addWidget(self.q4ChoiceRadioButton_2)
        self.q4Choice1LineEdit_2 = QtWidgets.QLineEdit(self.q4ChoiceGroupBox)
        self.q4Choice1LineEdit_2.setObjectName("q4Choice1LineEdit_2")
        self.q4ChoiceHorizontalLayout_2.addWidget(self.q4Choice1LineEdit_2)
        self.gridLayout_33.addLayout(self.q4ChoiceHorizontalLayout_2, 1, 0, 1, 1)
        self.q4ChoiceHorizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.q4ChoiceHorizontalLayout_3.setObjectName("q4ChoiceHorizontalLayout_3")
        self.q4ChoiceRadioButton_3 = QtWidgets.QRadioButton(self.q4ChoiceGroupBox)
        self.q4ChoiceRadioButton_3.setText("")
        self.q4ChoiceRadioButton_3.setObjectName("q4ChoiceRadioButton_3")
        self.q4ChoiceHorizontalLayout_3.addWidget(self.q4ChoiceRadioButton_3)
        self.q4Choice1LineEdit_3 = QtWidgets.QLineEdit(self.q4ChoiceGroupBox)
        self.q4Choice1LineEdit_3.setObjectName("q4Choice1LineEdit_3")
        self.q4ChoiceHorizontalLayout_3.addWidget(self.q4Choice1LineEdit_3)
        self.gridLayout_33.addLayout(self.q4ChoiceHorizontalLayout_3, 2, 0, 1, 1)
        self.q4ChoiceHorizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.q4ChoiceHorizontalLayout_4.setObjectName("q4ChoiceHorizontalLayout_4")
        self.q4ChoiceRadioButton_4 = QtWidgets.QRadioButton(self.q4ChoiceGroupBox)
        self.q4ChoiceRadioButton_4.setText("")
        self.q4ChoiceRadioButton_4.setObjectName("q4ChoiceRadioButton_4")
        self.q4ChoiceHorizontalLayout_4.addWidget(self.q4ChoiceRadioButton_4)
        self.q4Choice1LineEdit_4 = QtWidgets.QLineEdit(self.q4ChoiceGroupBox)
        self.q4Choice1LineEdit_4.setObjectName("q4Choice1LineEdit_4")
        self.q4ChoiceHorizontalLayout_4.addWidget(self.q4Choice1LineEdit_4)
        self.gridLayout_33.addLayout(self.q4ChoiceHorizontalLayout_4, 3, 0, 1, 1)
        self.q4VerticalLayout.addWidget(self.q4ChoiceGroupBox)
        self.q4Answer1abel = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.q4Answer1abel.setObjectName("q4Answer1abel")
        self.q4VerticalLayout.addWidget(self.q4Answer1abel)
        self.q4AnswerTextEdit = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_2)
        self.q4AnswerTextEdit.setObjectName("q4AnswerTextEdit")
        self.q4VerticalLayout.addWidget(self.q4AnswerTextEdit)
        self.q4ImageUrlLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.q4ImageUrlLabel.setObjectName("q4ImageUrlLabel")
        self.q4VerticalLayout.addWidget(self.q4ImageUrlLabel)
        self.q4ImageUrlLineEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.q4ImageUrlLineEdit.setObjectName("q4ImageUrlLineEdit")
        self.q4VerticalLayout.addWidget(self.q4ImageUrlLineEdit)
        self.q4ImageCaptionLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.q4ImageCaptionLabel.setObjectName("q4ImageCaptionLabel")
        self.q4VerticalLayout.addWidget(self.q4ImageCaptionLabel)
        self.q4ImageCaptionLineEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.q4ImageCaptionLineEdit.setObjectName("q4ImageCaptionLineEdit")
        self.q4VerticalLayout.addWidget(self.q4ImageCaptionLineEdit)
        self.quizVerticalLayout.addLayout(self.q4VerticalLayout)
        self.line_5 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.quizVerticalLayout.addWidget(self.line_5)
        self.q5VerticalLayout = QtWidgets.QVBoxLayout()
        self.q5VerticalLayout.setObjectName("q5VerticalLayout")
        self.q5Question1Label = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        self.q5Question1Label.setFont(font)
        self.q5Question1Label.setObjectName("q5Question1Label")
        self.q5VerticalLayout.addWidget(self.q5Question1Label)
        self.q5QuestionTextEdit = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_2)
        self.q5QuestionTextEdit.setObjectName("q5QuestionTextEdit")
        self.q5VerticalLayout.addWidget(self.q5QuestionTextEdit)
        self.q5ChoiceGroupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_2)
        self.q5ChoiceGroupBox.setMinimumSize(QtCore.QSize(0, 200))
        self.q5ChoiceGroupBox.setObjectName("q5ChoiceGroupBox")
        self.gridLayout_34 = QtWidgets.QGridLayout(self.q5ChoiceGroupBox)
        self.gridLayout_34.setObjectName("gridLayout_34")
        self.q5ChoiceHorizontalLayout_1 = QtWidgets.QHBoxLayout()
        self.q5ChoiceHorizontalLayout_1.setObjectName("q5ChoiceHorizontalLayout_1")
        self.q5ChoiceRadioButton_1 = QtWidgets.QRadioButton(self.q5ChoiceGroupBox)
        self.q5ChoiceRadioButton_1.setText("")
        self.q5ChoiceRadioButton_1.setObjectName("q5ChoiceRadioButton_1")
        self.q5ChoiceHorizontalLayout_1.addWidget(self.q5ChoiceRadioButton_1)
        self.q5Choice1LineEdit_1 = QtWidgets.QLineEdit(self.q5ChoiceGroupBox)
        self.q5Choice1LineEdit_1.setObjectName("q5Choice1LineEdit_1")
        self.q5ChoiceHorizontalLayout_1.addWidget(self.q5Choice1LineEdit_1)
        self.gridLayout_34.addLayout(self.q5ChoiceHorizontalLayout_1, 0, 0, 1, 1)
        self.q5ChoiceHorizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.q5ChoiceHorizontalLayout_2.setObjectName("q5ChoiceHorizontalLayout_2")
        self.q5ChoiceRadioButton_2 = QtWidgets.QRadioButton(self.q5ChoiceGroupBox)
        self.q5ChoiceRadioButton_2.setText("")
        self.q5ChoiceRadioButton_2.setObjectName("q5ChoiceRadioButton_2")
        self.q5ChoiceHorizontalLayout_2.addWidget(self.q5ChoiceRadioButton_2)
        self.q5Choice1LineEdit_2 = QtWidgets.QLineEdit(self.q5ChoiceGroupBox)
        self.q5Choice1LineEdit_2.setObjectName("q5Choice1LineEdit_2")
        self.q5ChoiceHorizontalLayout_2.addWidget(self.q5Choice1LineEdit_2)
        self.gridLayout_34.addLayout(self.q5ChoiceHorizontalLayout_2, 1, 0, 1, 1)
        self.q5ChoiceHorizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.q5ChoiceHorizontalLayout_3.setObjectName("q5ChoiceHorizontalLayout_3")
        self.q5ChoiceRadioButton_3 = QtWidgets.QRadioButton(self.q5ChoiceGroupBox)
        self.q5ChoiceRadioButton_3.setText("")
        self.q5ChoiceRadioButton_3.setObjectName("q5ChoiceRadioButton_3")
        self.q5ChoiceHorizontalLayout_3.addWidget(self.q5ChoiceRadioButton_3)
        self.q5Choice1LineEdit_3 = QtWidgets.QLineEdit(self.q5ChoiceGroupBox)
        self.q5Choice1LineEdit_3.setObjectName("q5Choice1LineEdit_3")
        self.q5ChoiceHorizontalLayout_3.addWidget(self.q5Choice1LineEdit_3)
        self.gridLayout_34.addLayout(self.q5ChoiceHorizontalLayout_3, 2, 0, 1, 1)
        self.q5ChoiceHorizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.q5ChoiceHorizontalLayout_4.setObjectName("q5ChoiceHorizontalLayout_4")
        self.q5ChoiceRadioButton_4 = QtWidgets.QRadioButton(self.q5ChoiceGroupBox)
        self.q5ChoiceRadioButton_4.setText("")
        self.q5ChoiceRadioButton_4.setObjectName("q5ChoiceRadioButton_4")
        self.q5ChoiceHorizontalLayout_4.addWidget(self.q5ChoiceRadioButton_4)
        self.q5Choice1LineEdit_4 = QtWidgets.QLineEdit(self.q5ChoiceGroupBox)
        self.q5Choice1LineEdit_4.setObjectName("q5Choice1LineEdit_4")
        self.q5ChoiceHorizontalLayout_4.addWidget(self.q5Choice1LineEdit_4)
        self.gridLayout_34.addLayout(self.q5ChoiceHorizontalLayout_4, 3, 0, 1, 1)
        self.q5VerticalLayout.addWidget(self.q5ChoiceGroupBox)
        self.q5Answer1abel = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.q5Answer1abel.setObjectName("q5Answer1abel")
        self.q5VerticalLayout.addWidget(self.q5Answer1abel)
        self.q5AnswerTextEdit = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_2)
        self.q5AnswerTextEdit.setObjectName("q5AnswerTextEdit")
        self.q5VerticalLayout.addWidget(self.q5AnswerTextEdit)
        self.q5ImageUrlLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.q5ImageUrlLabel.setObjectName("q5ImageUrlLabel")
        self.q5VerticalLayout.addWidget(self.q5ImageUrlLabel)
        self.q5ImageUrlLineEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.q5ImageUrlLineEdit.setObjectName("q5ImageUrlLineEdit")
        self.q5VerticalLayout.addWidget(self.q5ImageUrlLineEdit)
        self.q5ImageCaptionLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.q5ImageCaptionLabel.setObjectName("q5ImageCaptionLabel")
        self.q5VerticalLayout.addWidget(self.q5ImageCaptionLabel)
        self.q5ImageCaptionLineEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.q5ImageCaptionLineEdit.setObjectName("q5ImageCaptionLineEdit")
        self.q5VerticalLayout.addWidget(self.q5ImageCaptionLineEdit)
        self.quizVerticalLayout.addLayout(self.q5VerticalLayout)
        self.gridLayout_4.addLayout(self.quizVerticalLayout, 2, 0, 1, 1)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout.addWidget(self.splitter, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 853, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNew = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("document-new")
        self.actionNew.setIcon(icon)
        self.actionNew.setObjectName("actionNew")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("document-open")
        self.actionOpen.setIcon(icon)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setEnabled(False)
        icon = QtGui.QIcon.fromTheme("document-save")
        self.actionSave.setIcon(icon)
        self.actionSave.setObjectName("actionSave")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("help-about")
        self.actionAbout.setIcon(icon)
        self.actionAbout.setObjectName("actionAbout")
        self.actionNew_Quiz = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("list-add")
        self.actionNew_Quiz.setIcon(icon)
        self.actionNew_Quiz.setObjectName("actionNew_Quiz")
        self.actionPreview = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("document-print-preview")
        self.actionPreview.setIcon(icon)
        self.actionPreview.setObjectName("actionPreview")
        self.actionRemove_Quiz = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("list-remove")
        self.actionRemove_Quiz.setIcon(icon)
        self.actionRemove_Quiz.setObjectName("actionRemove_Quiz")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("system-shutdown")
        self.actionQuit.setIcon(icon)
        self.actionQuit.setObjectName("actionQuit")
        self.actionSave_As = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("document-save-as")
        self.actionSave_As.setIcon(icon)
        self.actionSave_As.setObjectName("actionSave_As")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_As)
        self.menuFile.addAction(self.actionNew_Quiz)
        self.menuFile.addAction(self.actionPreview)
        self.menuFile.addAction(self.actionRemove_Quiz)
        self.menuFile.addAction(self.actionQuit)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.actionQuit.triggered.connect(MainWindow.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Kwiz Kreator"))
        self.saveQuizButton.setText(_translate("MainWindow", "Save Quiz"))
        self.resetQuizButton.setText(_translate("MainWindow", "Reset Quiz"))
        self.titleLabel.setText(_translate("MainWindow", "Title"))
        self.titleLineEdit.setToolTip(_translate("MainWindow", "<html><head/><body><p>Main\n"
"                                                                    Quiz Title</p></body></html>\n"
"                                                                "))
        self.subtitleLabel.setText(_translate("MainWindow", "Subtitle"))
        self.subtitleLineEdit.setToolTip(_translate("MainWindow", "<html><head/><body><p>A\n"
"                                                                    brielf subtitle to further explain what the quiz is\n"
"                                                                    about.</p></body></html>\n"
"                                                                "))
        self.authorLabel.setText(_translate("MainWindow", "Author"))
        self.authorLineEdit.setToolTip(_translate("MainWindow", "<html><head/><body><p>Who\n"
"                                                                    wrote the quiz?</p></body></html>\n"
"                                                                "))
        self.publishOnLabel.setText(_translate("MainWindow", "Publish On"))
        self.publishOnDateEdit.setToolTip(_translate("MainWindow", "<html><head/><body><p>What\n"
"                                                                    date do you want to quiz to appear on?</p></body></html>\n"
"                                                                "))
        self.publishOnDateEdit.setDisplayFormat(_translate("MainWindow", "yyyy/MM/dd"))
        self.q1Question1Label.setText(_translate("MainWindow", "Question 1"))
        self.q1QuestionTextEdit.setToolTip(_translate("MainWindow", "<html><head/><body><p>What\'s\n"
"                                                                    the question you want folks to answer?</p></body></html>\n"
"                                                                "))
        self.q1ChoiceGroupBox.setTitle(_translate("MainWindow", "Choices"))
        self.q1ChoiceRadioButton_1.setToolTip(_translate("MainWindow", "<html><head/><body><p>Choose\n"
"                                                                                        which choice is the correct\n"
"                                                                                        answer</p></body></html>\n"
"                                                                                    "))
        self.q1Choice1LineEdit_1.setToolTip(_translate("MainWindow", "<html><head/><body><p>The\n"
"                                                                                        first possible answer</p></body></html>\n"
"                                                                                    "))
        self.q1ChoiceRadioButton_2.setToolTip(_translate("MainWindow", "<html><head/><body><p>Choose\n"
"                                                                                        which choice is the correct\n"
"                                                                                        answer</p></body></html>\n"
"                                                                                    "))
        self.q1Choice1LineEdit_2.setToolTip(_translate("MainWindow", "<html><head/><body><p>The\n"
"                                                                                        second possible answer</p></body></html>\n"
"                                                                                    "))
        self.q1ChoiceRadioButton_3.setToolTip(_translate("MainWindow", "<html><head/><body><p>Choose\n"
"                                                                                        which choice is the correct\n"
"                                                                                        answer</p></body></html>\n"
"                                                                                    "))
        self.q1Choice1LineEdit_3.setToolTip(_translate("MainWindow", "<html><head/><body><p>The\n"
"                                                                                        third possible answer</p></body></html>\n"
"                                                                                    "))
        self.q1ChoiceRadioButton_4.setToolTip(_translate("MainWindow", "<html><head/><body><p>Choose\n"
"                                                                                        which choice is the correct\n"
"                                                                                        answer</p></body></html>\n"
"                                                                                    "))
        self.q1Choice1LineEdit_4.setToolTip(_translate("MainWindow", "<html><head/><body><p>The\n"
"                                                                                        fourth possible answer</p></body></html>\n"
"                                                                                    "))
        self.q1Answer1abel.setText(_translate("MainWindow", "Answer"))
        self.q1AnswerTextEdit.setToolTip(_translate("MainWindow", "<html><head/><body><p>A\n"
"                                                                    longer explanation about the correct answer</p></body></html>\n"
"                                                                "))
        self.q1AnswerTextEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">                                                                    </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">                                                                     </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">                                                                     </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">                                                                 </p></body></html>"))
        self.q1ImageUrlLabel.setText(_translate("MainWindow", "Image URL"))
        self.q1ImageUrlLineEdit.setToolTip(_translate("MainWindow", "<html><head/><body><p>The\n"
"                                                                    url of the image you want to appear next to your\n"
"                                                                    answer</p></body></html>\n"
"                                                                "))
        self.q1ImageCaptionLabel.setText(_translate("MainWindow", "Image Caption"))
        self.q1ImageCaptionLineEdit.setToolTip(_translate("MainWindow", "<html><head/><body><p>Words\n"
"                                                                    you want appear under the picture</p></body></html>\n"
"                                                                "))
        self.q2Question1Label.setText(_translate("MainWindow", "Question 2"))
        self.q2QuestionTextEdit.setToolTip(_translate("MainWindow", "<html><head/><body><p>What\'s\n"
"                                                                            the question you want folks to answer?</p></body></html>\n"
"                                                                        "))
        self.q2ChoiceGroupBox.setTitle(_translate("MainWindow", "Choices"))
        self.q2ChoiceRadioButton_1.setToolTip(_translate("MainWindow", "<html><head/><body><p>Choose\n"
"                                                                                                which choice is the\n"
"                                                                                                correct answer</p></body></html>\n"
"                                                                                            "))
        self.q2Choice1LineEdit_1.setToolTip(_translate("MainWindow", "<html><head/><body><p>The\n"
"                                                                                                first possible answer</p></body></html>\n"
"                                                                                            "))
        self.q2ChoiceRadioButton_2.setToolTip(_translate("MainWindow", "<html><head/><body><p>Choose\n"
"                                                                                                which choice is the\n"
"                                                                                                correct answer</p></body></html>\n"
"                                                                                            "))
        self.q2Choice1LineEdit_2.setToolTip(_translate("MainWindow", "<html><head/><body><p>The\n"
"                                                                                                second possible answer</p></body></html>\n"
"                                                                                            "))
        self.q2ChoiceRadioButton_3.setToolTip(_translate("MainWindow", "<html><head/><body><p>Choose\n"
"                                                                                                which choice is the\n"
"                                                                                                correct answer</p></body></html>\n"
"                                                                                            "))
        self.q2Choice1LineEdit_3.setToolTip(_translate("MainWindow", "<html><head/><body><p>The\n"
"                                                                                                third possible answer</p></body></html>\n"
"                                                                                            "))
        self.q2ChoiceRadioButton_4.setToolTip(_translate("MainWindow", "<html><head/><body><p>Choose\n"
"                                                                                                which choice is the\n"
"                                                                                                correct answer</p></body></html>\n"
"                                                                                            "))
        self.q2Choice1LineEdit_4.setToolTip(_translate("MainWindow", "<html><head/><body><p>The\n"
"                                                                                                fourth possible answer</p></body></html>\n"
"                                                                                            "))
        self.q2Answer1abel.setText(_translate("MainWindow", "Answer"))
        self.q2AnswerTextEdit.setToolTip(_translate("MainWindow", "<html><head/><body><p>A\n"
"                                                                            longer explanation about the correct answer</p></body></html>\n"
"                                                                        "))
        self.q2AnswerTextEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">                                                                            </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">                                                                             </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">                                                                             </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">                                                                         </p></body></html>"))
        self.q2ImageUrlLabel.setText(_translate("MainWindow", "Image URL"))
        self.q2ImageUrlLineEdit.setToolTip(_translate("MainWindow", "<html><head/><body><p>The\n"
"                                                                            url of the image you want to appear next to\n"
"                                                                            your answer</p></body></html>\n"
"                                                                        "))
        self.q2ImageCaptionLabel.setText(_translate("MainWindow", "Image Caption"))
        self.q2ImageCaptionLineEdit.setToolTip(_translate("MainWindow", "<html><head/><body><p>Words\n"
"                                                                            you want appear under the picture</p></body></html>\n"
"                                                                        "))
        self.q3Question1Label.setText(_translate("MainWindow", "Question 3"))
        self.q3QuestionTextEdit.setToolTip(_translate("MainWindow", "<html><head/><body><p>What\'s\n"
"                                                                            the question you want folks to answer?</p></body></html>\n"
"                                                                        "))
        self.q3ChoiceGroupBox.setTitle(_translate("MainWindow", "Choices"))
        self.q3ChoiceRadioButton_1.setToolTip(_translate("MainWindow", "<html><head/><body><p>Choose\n"
"                                                                                                which choice is the\n"
"                                                                                                correct answer</p></body></html>\n"
"                                                                                            "))
        self.q3Choice1LineEdit_1.setToolTip(_translate("MainWindow", "<html><head/><body><p>The\n"
"                                                                                                first possible answer</p></body></html>\n"
"                                                                                            "))
        self.q3ChoiceRadioButton_2.setToolTip(_translate("MainWindow", "<html><head/><body><p>Choose\n"
"                                                                                                which choice is the\n"
"                                                                                                correct answer</p></body></html>\n"
"                                                                                            "))
        self.q3Choice1LineEdit_2.setToolTip(_translate("MainWindow", "<html><head/><body><p>The\n"
"                                                                                                second possible answer</p></body></html>\n"
"                                                                                            "))
        self.q3ChoiceRadioButton_3.setToolTip(_translate("MainWindow", "<html><head/><body><p>Choose\n"
"                                                                                                which choice is the\n"
"                                                                                                correct answer</p></body></html>\n"
"                                                                                            "))
        self.q3Choice1LineEdit_3.setToolTip(_translate("MainWindow", "<html><head/><body><p>The\n"
"                                                                                                third possible answer</p></body></html>\n"
"                                                                                            "))
        self.q3ChoiceRadioButton_4.setToolTip(_translate("MainWindow", "<html><head/><body><p>Choose\n"
"                                                                                                which choice is the\n"
"                                                                                                correct answer</p></body></html>\n"
"                                                                                            "))
        self.q3Choice1LineEdit_4.setToolTip(_translate("MainWindow", "<html><head/><body><p>The\n"
"                                                                                                fourth possible answer</p></body></html>\n"
"                                                                                            "))
        self.q3Answer1abel.setText(_translate("MainWindow", "Answer"))
        self.q3AnswerTextEdit.setToolTip(_translate("MainWindow", "<html><head/><body><p>A\n"
"                                                                            longer explanation about the correct answer</p></body></html>\n"
"                                                                        "))
        self.q3AnswerTextEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">                                                                            </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">                                                                             </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">                                                                             </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">                                                                         </p></body></html>"))
        self.q3ImageUrlLabel.setText(_translate("MainWindow", "Image URL"))
        self.q3ImageUrlLineEdit.setToolTip(_translate("MainWindow", "<html><head/><body><p>The\n"
"                                                                            url of the image you want to appear next to\n"
"                                                                            your answer</p></body></html>\n"
"                                                                        "))
        self.q3ImageCaptionLabel.setText(_translate("MainWindow", "Image Caption"))
        self.q3ImageCaptionLineEdit.setToolTip(_translate("MainWindow", "<html><head/><body><p>Words\n"
"                                                                            you want appear under the picture</p></body></html>\n"
"                                                                        "))
        self.q4Question1Label.setText(_translate("MainWindow", "Question 4"))
        self.q4QuestionTextEdit.setToolTip(_translate("MainWindow", "<html><head/><body><p>What\'s\n"
"                                                                    the question you want folks to answer?</p></body></html>\n"
"                                                                "))
        self.q4ChoiceGroupBox.setTitle(_translate("MainWindow", "Choices"))
        self.q4ChoiceRadioButton_1.setToolTip(_translate("MainWindow", "<html><head/><body><p>Choose\n"
"                                                                                        which choice is the correct\n"
"                                                                                        answer</p></body></html>\n"
"                                                                                    "))
        self.q4Choice1LineEdit_1.setToolTip(_translate("MainWindow", "<html><head/><body><p>The\n"
"                                                                                        first possible answer</p></body></html>\n"
"                                                                                    "))
        self.q4ChoiceRadioButton_2.setToolTip(_translate("MainWindow", "<html><head/><body><p>Choose\n"
"                                                                                        which choice is the correct\n"
"                                                                                        answer</p></body></html>\n"
"                                                                                    "))
        self.q4Choice1LineEdit_2.setToolTip(_translate("MainWindow", "<html><head/><body><p>The\n"
"                                                                                        second possible answer</p></body></html>\n"
"                                                                                    "))
        self.q4ChoiceRadioButton_3.setToolTip(_translate("MainWindow", "<html><head/><body><p>Choose\n"
"                                                                                        which choice is the correct\n"
"                                                                                        answer</p></body></html>\n"
"                                                                                    "))
        self.q4Choice1LineEdit_3.setToolTip(_translate("MainWindow", "<html><head/><body><p>The\n"
"                                                                                        third possible answer</p></body></html>\n"
"                                                                                    "))
        self.q4ChoiceRadioButton_4.setToolTip(_translate("MainWindow", "<html><head/><body><p>Choose\n"
"                                                                                        which choice is the correct\n"
"                                                                                        answer</p></body></html>\n"
"                                                                                    "))
        self.q4Choice1LineEdit_4.setToolTip(_translate("MainWindow", "<html><head/><body><p>The\n"
"                                                                                        fourth possible answer</p></body></html>\n"
"                                                                                    "))
        self.q4Answer1abel.setText(_translate("MainWindow", "Answer"))
        self.q4AnswerTextEdit.setToolTip(_translate("MainWindow", "<html><head/><body><p>A\n"
"                                                                    longer explanation about the correct answer</p></body></html>\n"
"                                                                "))
        self.q4AnswerTextEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">                                                                    </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">                                                                     </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">                                                                     </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">                                                                 </p></body></html>"))
        self.q4ImageUrlLabel.setText(_translate("MainWindow", "Image URL"))
        self.q4ImageUrlLineEdit.setToolTip(_translate("MainWindow", "<html><head/><body><p>The\n"
"                                                                    url of the image you want to appear next to your\n"
"                                                                    answer</p></body></html>\n"
"                                                                "))
        self.q4ImageCaptionLabel.setText(_translate("MainWindow", "Image Caption"))
        self.q4ImageCaptionLineEdit.setToolTip(_translate("MainWindow", "<html><head/><body><p>Words\n"
"                                                                    you want appear under the picture</p></body></html>\n"
"                                                                "))
        self.q5Question1Label.setText(_translate("MainWindow", "Question 5"))
        self.q5QuestionTextEdit.setToolTip(_translate("MainWindow", "<html><head/><body><p>What\'s\n"
"                                                                    the question you want folks to answer?</p></body></html>\n"
"                                                                "))
        self.q5ChoiceGroupBox.setTitle(_translate("MainWindow", "Choices"))
        self.q5ChoiceRadioButton_1.setToolTip(_translate("MainWindow", "<html><head/><body><p>Choose\n"
"                                                                                        which choice is the correct\n"
"                                                                                        answer</p></body></html>\n"
"                                                                                    "))
        self.q5Choice1LineEdit_1.setToolTip(_translate("MainWindow", "<html><head/><body><p>The\n"
"                                                                                        first possible answer</p></body></html>\n"
"                                                                                    "))
        self.q5ChoiceRadioButton_2.setToolTip(_translate("MainWindow", "<html><head/><body><p>Choose\n"
"                                                                                        which choice is the correct\n"
"                                                                                        answer</p></body></html>\n"
"                                                                                    "))
        self.q5Choice1LineEdit_2.setToolTip(_translate("MainWindow", "<html><head/><body><p>The\n"
"                                                                                        second possible answer</p></body></html>\n"
"                                                                                    "))
        self.q5ChoiceRadioButton_3.setToolTip(_translate("MainWindow", "<html><head/><body><p>Choose\n"
"                                                                                        which choice is the correct\n"
"                                                                                        answer</p></body></html>\n"
"                                                                                    "))
        self.q5Choice1LineEdit_3.setToolTip(_translate("MainWindow", "<html><head/><body><p>The\n"
"                                                                                        third possible answer</p></body></html>\n"
"                                                                                    "))
        self.q5ChoiceRadioButton_4.setToolTip(_translate("MainWindow", "<html><head/><body><p>Choose\n"
"                                                                                        which choice is the correct\n"
"                                                                                        answer</p></body></html>\n"
"                                                                                    "))
        self.q5Choice1LineEdit_4.setToolTip(_translate("MainWindow", "<html><head/><body><p>The\n"
"                                                                                        fourth possible answer</p></body></html>\n"
"                                                                                    "))
        self.q5Answer1abel.setText(_translate("MainWindow", "Answer"))
        self.q5AnswerTextEdit.setToolTip(_translate("MainWindow", "<html><head/><body><p>A\n"
"                                                                    longer explanation about the correct answer</p></body></html>\n"
"                                                                "))
        self.q5AnswerTextEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">                                                                    </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">                                                                     </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">                                                                     </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">                                                                 </p></body></html>"))
        self.q5ImageUrlLabel.setText(_translate("MainWindow", "Image URL"))
        self.q5ImageUrlLineEdit.setToolTip(_translate("MainWindow", "<html><head/><body><p>The\n"
"                                                                    url of the image you want to appear next to your\n"
"                                                                    answer</p></body></html>\n"
"                                                                "))
        self.q5ImageCaptionLabel.setText(_translate("MainWindow", "Image Caption"))
        self.q5ImageCaptionLineEdit.setToolTip(_translate("MainWindow", "<html><head/><body><p>Words\n"
"                                                                    you want appear under the picture</p></body></html>\n"
"                                                                "))
        self.menuFile.setTitle(_translate("MainWindow", "&File"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionNew.setToolTip(_translate("MainWindow", "Create a new Trail Trivia File"))
        self.actionNew.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionOpen.setToolTip(_translate("MainWindow", "Open a Trail Trivia file"))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave.setToolTip(_translate("MainWindow", "Save your Trail Trivia file"))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionNew_Quiz.setText(_translate("MainWindow", "New Quiz"))
        self.actionPreview.setText(_translate("MainWindow", "Preview"))
        self.actionRemove_Quiz.setText(_translate("MainWindow", "Remove Quiz"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionSave_As.setText(_translate("MainWindow", "Save As"))
        self.actionSave_As.setShortcut(_translate("MainWindow", "Ctrl+Shift+S"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
